### ISSUE TITLE
Does not support iPad?

### ISSUE THREAD

**Issue by jzhw0130** [pengfeiw/react-paint#2]
Open demo (https://pengfeiw.github.io/react-paint/) on iPad, it does not work.

Or try iPad size on Web, does not work, too.

<img width="777" alt="Screenshot 2021-12-30 at 9 46 58 PM" src="https://user-images.githubusercontent.com/12521790/147757720-7c5ad502-1fe8-4798-af4d-4bb0af7098ab.png">

**Comment by pengfeiw** [comment]
It does not support touch event, yet. I will add it.

**Comment by jzhw0130** [comment]
@pengfeiw 
cool, thx

**Comment by pengfeiw** [comment]
@jzhw0130 I update the code. It support touchscreen devices, now.

**Comment by jzhw0130** [comment]
@pengfeiw 

cool!  👍 🥇 

It works pretty well on iPad and iPhone.

A minor issue existed when I tried the `filling` feature on web with `iPad` size, the web did not response at all after I `filling` an area.
Refer to the below screenshot.

<img width="536" alt="Screenshot 2022-01-01 at 11 49 04 AM" src="https://user-images.githubusercontent.com/12521790/147843656-6dcf665d-0ba0-47be-85b7-917027e45b7f.png">

**Comment by pengfeiw** [comment]
@jzhw0130 
txh, I commited some code, You can try it again. [fix filling feature](https://github.com/pengfeiw/react-paint/commit/4df7ba016c3e80daf41cafea2e7343e08731c607)

**Comment by jzhw0130** [comment]
@pengfeiw  

cool, thx
