### ISSUE TITLE
Filling issue

### ISSUE THREAD

**Issue by jzhw0130** [pengfeiw/react-paint#4]
Will leave some `weird` edge after filling.

How to replicate:
1. Fill the whole background with green color, refer to: screenshot-1
2. Draw a circle with red color,  refer to: screenshot-2
3. Fill red color inside the circle, refer to:  screenshot-3
4. Fill red color outside the circle, refer to:  screenshot-4

By right all the canvas will the in red color, but actually not.

Could you help on this?
Thank you.

<img width="1564" alt="screenshot-1" src="https://user-images.githubusercontent.com/12521790/149511799-6297f315-51fb-431a-80e9-5397ffac0511.png">
<img width="1554" alt="screenshot-2" src="https://user-images.githubusercontent.com/12521790/149511815-82451fa1-7511-4940-95ef-423e67687b57.png">
<img width="1556" alt="screenshot-3" src="https://user-images.githubusercontent.com/12521790/149511822-864d2439-8f13-454b-8964-6c4ed2d9d230.png">
<img width="1559" alt="screenshot-4" src="https://user-images.githubusercontent.com/12521790/149511836-c97cf7c5-82fc-42df-8021-8329bb767e7f.png">

**Comment by pengfeiw** [comment]
Thank you for helping to find bug. The weird edge caused by `lineWidth`, you can get more info [here](https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors), but I don't know how to fix it yet  .... Contributions are welcome.

**Comment by pengfeiw** [comment]
> The line width is the thickness of the stroke centered on the given path. In other words, the area that's drawn extends to half the line width on either side of the path.

So the stroke color may not be the same with the color I set, cause `filling feature` work bad on edge.

**Comment by pengfeiw** [comment]
I fix it 😄

**Comment by jzhw0130** [comment]
@pengfeiw 

cool 👍 🥇 

So the issue is:
After filling, some edge pix color neither is same as `filling` color, nor same as `original` color, correct?
So your solution is fill these edge pix with `filling` color one more time after filling.

**Comment by jzhw0130** [comment]
hmm 
the root issue is :  canvas.stroke() draw the path which has different color with stroke color, correct?

**Comment by pengfeiw** [comment]
yes, there may be another way to fix it.

**Comment by jzhw0130** [comment]
@pengfeiw 

ya, maybe another solution:
1. create another canvas with same size and background color (#000)
2. draw shape on the new canvas with stroke color (#fff)
3. for loop the imageData of the new canvas, choose all pix with color #000, and fill the same position pix on the original canvas with specific stroke color.

But seems no big difference with your solution, lol
